lib: fix compilation with NASM 2.15 (fix for #75"
Fixed compilation when using NASM 2.15, as it was throwing the
following warnings, due to an additional (and unnecessary) comma:
error: dropping trailing empty parameter in call to multi-line macro `UNION' [-w+error=macro-params-legacy]